# Generated by Django 5.2.6 on 2025-10-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_issuer', models.CharField(blank=True, max_length=100)),
                ('card_last_4', models.CharField(blank=True, max_length=4)),
                ('card_variant', models.CharField(blank=True, max_length=100)),
                ('billing_cycle', models.CharField(blank=True, max_length=100)),
                ('payment_due_date', models.CharField(blank=True, max_length=100)),
                ('total_balance', models.CharField(blank=True, max_length=100)),
                ('transaction_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.uploadedfile')),
            ],
        ),
    ]
